### PR TITLE
Register go-lyft-linters (`ambiguousliteral`)

### PR DESCRIPTION
**Pull request by connor15mcc**
Register `ambiguousliteral` from `go-lyft-linters@v0.1.1`

See this spec https://docs.google.com/document/d/17zxZIJR3a6Rj6NpjYYBkKAEDObZr-x0V6h9iID5Ea4g/edit?tab=t.0 about plugin registration within golangci-lint

And this quick doc about the registered linter: https://docs.google.com/document/d/1FydaYKH0o2kNVmqHwvvSgWYmLsgku8W3PIMoBraSrOM/edit?tab=t.0#heading=h.pxnj6qktbeyy (introduced in https://github.com/lyft/go-lyft-linters/pull/2)

### CODE REVIEW

**Comment by connor15mcc** [comment]
PTAL @hanzo @lyft/app-foundations

**Review by hanzo — APPROVED** [review]
💯

**Comment by hanzo** [comment]
@connor15mcc after merging this, could you update this repo to the latest upstream? And update this doc with the new steps to re-apply this custom linter change: 

https://github.com/lyft/precommit-private/blob/main/docs/runbook.md#upgrading-to-a-new-version-of-golangci-lint

**Comment by connor15mcc** [comment]
Happily!

**Pull request merged**
